#!/bin/bash
# to bootstrap a new machine:
#git clone --bare git@github.com:poleguy/dotfiles.git $HOME/.dotfiles
#alias git_dotfiles="env GIT_WORK_TREE=$HOME GIT_DIR=$HOME/.dotfiles git"
#git_dotfiles checkout -m master dofiles_setup 

function git_dotfiles {
   env GIT_WORK_TREE=$HOME GIT_DIR=$HOME/.dotfiles git $@
}

git clone --bare git@github.com:poleguy/dotfiles.git $HOME/.dotfiles

# this won't work without first removing pre-existing working files

mkdir -p .dotfiles-backup
git_dotfiles checkout master
if [ $? = 0 ]; then
  echo "Checked out config.";
  else
    echo "Backing up pre-existing dot files.";
    git_dotfiles checkout master 2>&1 | egrep "^\s+" | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
fi;
git_dotfiles checkout master
git_dotfiles config --local status.showUntrackedFiles no

conda activate base
pip install hdl_checker
